// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCupatdn0b1PFMuunQY02vLw4LEyvTvFwg',
    appId: '1:177442623900:web:d198d637e33671109c7859',
    messagingSenderId: '177442623900',
    projectId: 'angko-6a438',
    authDomain: 'angko-6a438.firebaseapp.com',
    databaseURL:
        'https://angko-6a438-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'angko-6a438.appspot.com',
    measurementId: 'G-S21PDV0Q2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC105gqJ-33j12xTNTjhiu0LsbqR-28A28',
    appId: '1:177442623900:android:20ceb830043de92f9c7859',
    messagingSenderId: '177442623900',
    projectId: 'angko-6a438',
    databaseURL:
        'https://angko-6a438-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'angko-6a438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3bsXjuzUEwP-iNE14FYZFY7O9dMJni-g',
    appId: '1:177442623900:ios:0df49e135d249ca59c7859',
    messagingSenderId: '177442623900',
    projectId: 'angko-6a438',
    databaseURL:
        'https://angko-6a438-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'angko-6a438.appspot.com',
    iosBundleId: 'com.example.angko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3bsXjuzUEwP-iNE14FYZFY7O9dMJni-g',
    appId: '1:177442623900:ios:0df49e135d249ca59c7859',
    messagingSenderId: '177442623900',
    projectId: 'angko-6a438',
    databaseURL:
        'https://angko-6a438-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'angko-6a438.appspot.com',
    iosBundleId: 'com.example.angko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCupatdn0b1PFMuunQY02vLw4LEyvTvFwg',
    appId: '1:177442623900:web:40eec0fa42354df69c7859',
    messagingSenderId: '177442623900',
    projectId: 'angko-6a438',
    authDomain: 'angko-6a438.firebaseapp.com',
    databaseURL:
        'https://angko-6a438-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'angko-6a438.appspot.com',
    measurementId: 'G-T1LQ5PT21X',
  );
}
